name: Continuous Integration
on:
  pull_request

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
    
      - name: Validate
        # uses: cwtools/cwtools-action@v1.0.0
        uses: Undeadbanana/cwtools-action-ck3test@v1.0.1
        with:
          game: ck3
          